Repository Chilled-Run/ChilledCafe, pull requests merged in 2022-12, with the labels that each got.

#83 [feat] #80 #81 #82 커스텀 런치스크린 구현 및 네트워크 작업 로직 변경
  ChilledCafe.xcodeproj/project.pbxproj
  ChilledCafe/Assets.xcassets/SplashView.imageset/Contents.json
  ChilledCafe/Assets.xcassets/SplashView.imageset/SplashView.png
  ChilledCafe/Assets.xcassets/SplashView.imageset/SplashView@2x.png
  ChilledCafe/Assets.xcassets/SplashView.imageset/SplashView@3x.png
  ChilledCafe/Assets.xcassets/WhiteAppTitle.imageset/Contents.json
  ChilledCafe/Assets.xcassets/WhiteAppTitle.imageset/WhiteLogo.png
  ChilledCafe/ChilledCafeApp.swift
  ChilledCafe/Data/temparyData.swift
  ChilledCafe/FIrebase/FirebaseStorageManager.swift
  ChilledCafe/Info.plist
  ChilledCafe/Model/Cafe.swift
  ChilledCafe/Model/Cafes.swift
  ChilledCafe/Views/Bookmark/MyBookmarkView.swift
  ChilledCafe/Views/CafeDetail/CafeDetailView.swift
  ChilledCafe/Views/CafeDetail/Info.swift
  ChilledCafe/Views/CafeDetail/Menu.swift
  ChilledCafe/Views/CafeDetail/Mood.swift
  ChilledCafe/Views/CafeDetail/OffsetModifier.swift
  ChilledCafe/Views/CafeList/CafeListView.swift
  ChilledCafe/Views/DetailPages/BODetailView.swift
  ChilledCafe/Views/DetailPages/DetailInfoView.swift
  ChilledCafe/Views/DetailPages/DetailTagView.swift
  ChilledCafe/Views/LaunchScreen/LaunchScreenView.swift
  ChilledCafe/Views/Main/FullCardScrollView.swift
  ChilledCafe/Views/Main/FullCardView.swift
  ChilledCafe/Views/Main/MainView.swift
Labels: ✨ Feat, 🛠 Refactor, 🐘 [Dev] Terry

#96 [feat] #95 공간 스토리 뷰 추가
  ChilledCafe.xcodeproj/project.pbxproj
  ChilledCafe/Data/temparyData.swift
  ChilledCafe/Views/DetailPages/BODetailView.swift
  ChilledCafe/Views/DetailPages/GuestLogView.swift
  ChilledCafe/Views/DetailPages/StorySmallView.swift
  ChilledCafe/Views/VisitLogView/CreateStoryView.swift
  ChilledCafe/Views/VisitLogView/StoryView.swift
Labels: ✨ Feat, 🍪 [Dev] Cookie

#93 [refactor] #90 런치스크린 이미지 변경
  ChilledCafe/Assets.xcassets/Launch.imageset/Contents.json
  ChilledCafe/Assets.xcassets/Launch.imageset/Launch.png
  ChilledCafe/Assets.xcassets/Launch.imageset/Launch@2x.png
  ChilledCafe/Assets.xcassets/Launch.imageset/Launch@3x.png
  ChilledCafe/Assets.xcassets/SplashView.imageset/SplashView.png
  ChilledCafe/Assets.xcassets/SplashView.imageset/SplashView@2x.png
  ChilledCafe/Assets.xcassets/SplashView.imageset/SplashView@3x.png
  ChilledCafe/FIrebase/FirebaseStorageManager.swift
  ChilledCafe/Info.plist
  ChilledCafe/Views/LaunchScreen/LaunchScreenView.swift
  ChilledCafe/Views/Main/MainView.swift
Labels: 🛠 Refactor, 🔥 HotFix, 🐘 [Dev] Terry

#104 [refactor] #87 탭뷰 모양 변경
  ChilledCafe/Assets.xcassets/home.imageset/Contents.json
  ChilledCafe/Assets.xcassets/home.imageset/home.svg
  ChilledCafe/ChilledCafeApp.swift
  ChilledCafe/Views/Main/FullCardScrollView.swift
  ChilledCafe/Views/Main/HorizontalScrollMenuBarView.swift
  ChilledCafe/Views/Main/MainView.swift
  ChilledCafe/Views/Main/TabBarIcon.swift
Labels: ✨ Feat, 🛠 Refactor, 🐘 [Dev] Terry

#103 [feat] #100 CommentView 구현
  ChilledCafe.xcodeproj/project.pbxproj
  ChilledCafe/Assets.xcassets/foot.imageset/Contents.json
  ChilledCafe/Assets.xcassets/foot.imageset/foot.svg
  ChilledCafe/Assets.xcassets/pastelBlueOpacity0.2.colorset/Contents.json
  ChilledCafe/Assets.xcassets/pastelGreenOpacity0.2.colorset/Contents.json
  ChilledCafe/ChilledCafeApp.swift
  ChilledCafe/Data/temparyData.swift
  ChilledCafe/Extension/ViewExtension.swift
  ChilledCafe/Extension/keyboardExtension.swift
  ChilledCafe/Info.plist
  ChilledCafe/Model/Story.swift
  ChilledCafe/Views/ARView/ARButtons.swift
  ChilledCafe/Views/ARView/ARMainView.swift
  ChilledCafe/Views/DetailPages/BODetailView.swift
  ChilledCafe/Views/VisitLogView/CommnetView.swift
  ChilledCafe/Views/VisitLogView/CreateStoryView.swift
  ChilledCafe/Views/VisitLogView/StoryContentView.swift
  ChilledCafe/Views/VisitLogView/StoryView.swift
  ChilledCafe/Views/VisitLogView/TextView.swift
Labels: ✨ Feat, 🍪 [Dev] Cookie

#105 [feat] #102 스토리 삭제 시 알림창
  .DS_Store
  ChilledCafe/.DS_Store
  ChilledCafe/Views/.DS_Store
  ChilledCafe/Views/ARView/ARMainView.swift
  ChilledCafe/Views/VisitLogView/CreateStoryView.swift
Labels: ✨ Feat, 🍪 [Dev] Cookie

#116 [feat] #115 AllStoryView를 만들었어요
  ChilledCafe.xcodeproj/project.pbxproj
  ChilledCafe/Assets.xcassets/ARFootprints/bearPawPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/bearPawPrint.imageset/bearPawPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/birdFootPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/birdFootPrint.imageset/birdFootPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/catPawPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/catPawPrint.imageset/catPawPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/dogFootPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/dogFootPrint.imageset/dogFootPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/duckFootPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/duckFootPrint.imageset/duckFootPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/horsePawPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/horsePawPrint.imageset/horsePawPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/leftFootPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/leftFootPrint.imageset/leftFootPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/rightFootPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/rightFootPrint.imageset/rightFootPrint.png
  ChilledCafe/FIrebase/FirebaseStorageManager.swift
  ChilledCafe/Views/ARView/ARMainView.swift
  ChilledCafe/Views/DetailPages/BODetailView.swift
  ChilledCafe/Views/DetailPages/GuestLogView.swift
  ChilledCafe/Views/VisitLogView/AllStoryView.swift
  ChilledCafe/Views/VisitLogView/CreateStoryView.swift
  ChilledCafe/Views/VisitLogView/StoryContentView.swift
  ChilledCafe/Views/VisitLogView/StoryView.swift
Labels: ✨ Feat, 🍪 [Dev] Cookie

#118 [feat] #113 자신의 스토리 보여주기
  ChilledCafe.xcodeproj/project.pbxproj
  ChilledCafe/Views/ARView/ARMainView.swift
  ChilledCafe/Views/ARView/CheckCurrentLocationView.swift
  ChilledCafe/Views/DetailPages/GuestLogView.swift
  ChilledCafe/Views/VisitLogView/CommnetView.swift
  ChilledCafe/Views/VisitLogView/CreateStoryView.swift
  ChilledCafe/Views/VisitLogView/StoryView.swift
Labels: ✨ Feat, 🍪 [Dev] Cookie

#121 [feat] #120 bookmark Toggle
  ChilledCafe/Views/DetailPages/DetailInfoView.swift
  ChilledCafe/Views/Main/FullCardView.swift
Labels: ✨ Feat, 🍪 [Dev] Cookie

#123 [feat] #122 발자국 이미지 보이게 개선
  ChilledCafe/Assets.xcassets/ARFootprints/bearFootPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/bearFootPrint.imageset/bearPawPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/catFootPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/catFootPrint.imageset/catPawPrint.png
  ChilledCafe/Assets.xcassets/ARFootprints/horseFootPrint.imageset/Contents.json
  ChilledCafe/Assets.xcassets/ARFootprints/horseFootPrint.imageset/horsePawPrint.png
  ChilledCafe/Views/ARView/ARMainView.swift
  ChilledCafe/Views/VisitLogView/CommnetView.swift
  ChilledCafe/Views/VisitLogView/CreateStoryView.swift
  ChilledCafe/Views/VisitLogView/StoryContentView.swift
  ChilledCafe/Views/VisitLogView/StoryView.swift
Labels: ✨ Feat, 🍪 [Dev] Cookie
